version: "3.9"

services:
  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c 'max_connections=200'

  decrease:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db